#系统配置入口点 根据环境变量加载相应的application-${sysENV}.yaml
spring:
  profiles:
    active: dev
  application:
    name: jz-archetype


management:
  endpoints:
    web:
      exposure:
        include: *
  metrics:
    tags:
      application: ${spring.application.name}
